import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "./components/Footer";
import { Toaster } from "@/app/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Audiophiile-ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("h-full antialiased", inter.className)}>
        <main className="flex flex-col min-h-screen">
          <div className="flex-grow flex-1">
            {children}
            <Toaster position="bottom-center" />
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
